In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

In [2]:
np.random.seed(0)
tf.set_random_seed(1234)

In [3]:
def mask(T=200):
    mask = np.zeros(T)
    indices = np.random.permutation(T)[:2]
    mask[indices] = 1  # randomly initialize two indices to 1
    return mask


def toy_problem(N=10, T=200):
    signals = np.random.uniform(low=0.0, high=1.0, size=(N, T))
    masks = np.zeros((N, T))
    for i in range(N):
        masks[i] = mask(T)

    data = np.zeros((N, T, 2))
    data[:, :, 0] = signals[:]
    data[:, :, 1] = masks[:]
    target = (signals * masks).sum(axis=1).reshape(N, 1)

    return (data, target)

In [5]:
np.random.permutation(9)[:2]

array([3, 1])

In [9]:
a = np.arange(9).reshape(3,3)
a[1] = np.arange(3)

In [10]:
a

array([[0, 1, 2],
       [0, 1, 2],
       [6, 7, 8]])

In [12]:
a.sum(axis=)

array([ 6,  9, 12])